GET http://localhost:3001/try-qs?a[]=2&a[]=3bill



###

POST http://localhost:3001/try-post
Content-Type: application/x-www-form-urlencoded

name=david&gender=male

###

POST http://localhost:3001/try-post
Content-Type: application/json

{"name":"lora","gender":"female"}
